<?php

namespace App\Repository;

use App\Entity\Video;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @extends ServiceEntityRepository<Video>
 */
class VideoRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Video::class);
    }

    public function save(Video $video){
        $this->getEntityManager()->persist($video);
        $this->getEntityManager()->flush();
    }

//    public function findOneByUid(string $uid): object|null
//    {
//        $criteria = new Criteria();
//        $criteria->where(Criteria::expr()->eq('uid', $uid));
//        return parent::findOneBy($criteria); // TODO: Change the autogenerated stub
//    }

//        /**
//         * @return Video[] Returns an array of Video objects
//         */
//        public function findByUid($value): array
//        {
//            return $this->createQueryBuilder('v')
//                ->andWhere('v.uid = :val')
//                ->setParameter('val', $value)
//                ->orderBy('v.recordTime', 'ASC')
//                ->getQuery()
//                ->getResult()
//            ;
//        }

    //    public function findOneBySomeField($value): ?Video
    //    {
    //        return $this->createQueryBuilder('v')
    //            ->andWhere('v.exampleField = :val')
    //            ->setParameter('val', $value)
    //            ->getQuery()
    //            ->getOneOrNullResult()
    //        ;
    //    }
}
